# Railway deployment configuration
# This file tells Railway how to deploy your app

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/data"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
FLASK_ENV = "production"
